### ISSUE TITLE
regarding libsteamnetworkingsockets

### ISSUE THREAD

**Issue by markus-wa** [OpenIW/goldberg_emulator#1]
hey - I saw you made some changes regarding disabling libsteamnetworkingsockets here

can you elaborate on this? I'm having trouble with CS:GO crashing due to the following errors on ubuntu 20.04 - which used to work before.

do you know anything about this? I've asked in the original repo, but figured you might have an idea as well :sweat_smile: 

gdb backtrace:
```
Core was generated by `/opt/csgo/csgo_linux64 -steam -console -insecure -untrusted -novideo -namedpipe'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f61026c3e00 (LWP 787))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f6102a35859 in __GI_abort () at abort.c:79
#2  0x00007f61028cd911 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f61028d938c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f61028d93f7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f61028d96a9 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f61028d07d5 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007f60e3db401e in ?? () from /opt/csgo/bin/linux64/libsteamnetworkingsockets.so
#8  0x00007f60e3d82438 in ?? () from /opt/csgo/bin/linux64/libsteamnetworkingsockets.so
#9  0x00007f60e3d92135 in ?? () from /opt/csgo/bin/linux64/libsteamnetworkingsockets.so
#10 0x00007f60e3d9252f in SteamDatagramClient_Init_InternalV9 () from /opt/csgo/bin/linux64/libsteamnetworkingsockets.so
#11 0x00007f60e786e0a2 in ?? () from /opt/csgo/bin/linux64/engine_client.so
#12 0x00007f60e78c6d27 in ?? () from /opt/csgo/bin/linux64/engine_client.so
#13 0x00007f610245a257 in ?? ()
#14 0x0000000000000000 in ?? ()
```

**Comment by wroyca** [comment]
This fork is specifically tailored to our needs with OpenIW and this module was disabled because it could not be compiled in the first place — maybe we are doing something wrong? In any case, we are not able to help you and I am closing this issue hoping that someone on the official goldberg repository will be a better fit to assist you. 😅 🙏

**Comment by markus-wa** [comment]
no worries, makes sense!
